// <auto-generated />
using System;
using BioDash.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioDash.Infrastructure.Migrations
{
    [DbContext(typeof(BioDashDbContext))]
    partial class BioDashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("BioDash.Domain.Entities.CicloProducao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TanqueId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ciclos");
                });

            modelBuilder.Entity("BioDash.Domain.Entities.Tanque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("CapacidadeLitros")
                        .HasColumnType("REAL");

                    b.Property<double>("NivelAtual")
                        .HasColumnType("REAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimoCiclo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tanques");
                });
#pragma warning restore 612, 618
        }
    }
}
